### ISSUE TITLE
Not appearing in mod menu BS v1.15.0

### ISSUE THREAD

**Issue by YoYoNinjaBoy** [rithik-b/BetterLatencyAdjuster#2]
dll placed in common/beat saber/Plugins
BSML.dll present (but I don't see it in ModAssistant so maybe its outdated???)
BS_Utils up to date

**Comment by rithik-b** [comment]
This mod is no longer supported, it’s been over a year since any updates and that of course will break any mod.
This repo will be archived.

**Comment by ErisApps** [comment]
So yeah, the mod is severely outdated, but I'm working on updating it for the latest version as we speak.
